# Generated by Django 6.1 on 2026-08-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_car_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order_line',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(),
        ),
    ]
