# Generated by Django 6.1 on 2026-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_orderline_delete_order_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Patvirtinta'), ('v', 'Vykdoma'), ('a', 'Atšaukta')], default='p', max_length=1, verbose_name='Status'),
        ),
    ]
